### ISSUE TITLE
Why alluvial diagram will be overlap in the same place when I use the parcats-shiny?

### ISSUE THREAD

**Issue by xiaowei3223** [erblast/parcats#6]
Hi, I got a problem. I don't know why alluvial diagram will be overlap in the same place when I use the parcats-shiny?
What should I do about it?
The shiny app is on [https://github.com/xiaowei3223/git_issues/tree/main/issues_for_parcats](https://github.com/xiaowei3223/git_issues/tree/main/issues_for_parcats)

**Comment by erblast** [comment]
Thank you for bringing this up. I can confirm that this is a problem that I have not been able to solve yet. I tried solving it before I initially submitted to CRAN but was not able to. I will take another look but do not expect a solution anytime soon.

**Comment by erblast** [comment]
it was easier to fix then I thought. It should work now when you use the new dev version from github
